on:
  push:
    branches:
      - main

jobs:
  dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DEV EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          timeout: 60s
          script: |
            sudo apt update -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
            sudo rm -rf /var/www/html/*
            sed "s/ENV_NAME/${{ vars.ENV_NAME }}/g" index.html | sudo tee /var/www/html/index.html

  test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    environment: test
    needs: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to TEST EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          timeout: 60s
          script: |
            sudo apt update -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
            sudo rm -rf /var/www/html/*
            sed "s/ENV_NAME/${{ vars.ENV_NAME }}/g" index.html | sudo tee /var/www/html/index.html

  prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    environment: prod
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          timeout: 60s
          script: |
            sudo apt update -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
            sudo rm -rf /var/www/html/*
            sed "s/ENV_NAME/${{ vars.ENV_NAME }}/g" index.html | sudo tee /var/www/html/index.html
